import dotenv from "dotenv";
dotenv.config();

const p = process.env;

export const ENV = {
    APP_PORT: p.PORT || 4000,
    APP_HOST: p.HOST || "http://localhost",
    MAIL_DOMAIN: p.MAILGUN_DOMAIN!,
    MAIL_FROM: p.MAIL_FROM || "dirtypicksmx@gmail.com",
    FRONT_HOST: p.FRONT_HOST,
    MAIL_CLIENT: p.MAIL_CLIENT,
    MAIL_SECRET: p.MAIL_SECRET,
    MAIL_GCLIENT: p.MAIL_GCLIENT,
    MAIL_GSECRET: p.MAIL_GSECRET,
    MAIL_REFRESH_TOKEN: p.MAIL_REFRESH_TOKEN,
    MAIL_REDIRECT_URI: p.MAIL_REDIRECT_URI,
    STRIPE_PUBLIC_KEY: p.STRIPE_PUBLIC_KEY,
    STRIPE_SECRET_KEY: p.STRIPE_SECRET_KEY!,
    STRIPE_WEBHOOK_SECRET: p.STRIPE_WEBHOOK_SECRET!
}